spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/home_stock
    username: home_stock_user
    password: home_stock_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

#    JWT_SECRET="your-long-secret-key-your-long-secret-key" ./mvnw spring-boot:run -Dspring-boot.run.profiles=local