spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/home_stock
    username: home_stock_user
    password: home_stock_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
