CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users(
    id BIGSERIAL PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE  DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL ,
    display_name VARCHAR(100) NOT NULL ,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL  DEFAULT  CURRENT_TIMESTAMP

)